import "./globals.css";
import type { Metadata } from "next";
// import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./auth/Provider";
import Script from "next/script";
import GoogleAnalyticsScript from "./GoogleAnalyticsScript";

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
// });

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "500"],
//   display: "swap",
//   adjustFontFallback: false,
// });

// const poppins = localFont({
//   src: "../public//fonts/poppins-regular-webfont.woff2",
//   variable: "--font-poppins",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Naseer Digital Store",
    description: "Buy digital pdfs, code, images, videos etc",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript />
      <body>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
